# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TELbPE7jaV74h5IYcYFS8_H7_2V4XPKV
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
import gradio as gr

df = pd.read_csv('/content/Mental_Health_and_Social_Media_Balance_Dataset.csv')
df.head()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.corr(numeric_only=True)

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

sns.set_style('whitegrid')
plt.figure(figsize=(7,5))

sns.countplot(x='Stress_Level(1-10)', data=df, palette='coolwarm')

plt.title('Distribution of Stress Levels among Individuals')
plt.xlabel('Stress Level (1 to 10)')
plt.ylabel('Number of People')
plt.show()

age = int(input("Enter your age: "))
screen_time = float(input("Daily screen time (hrs): "))
stress = int(input("Stress level (1-10): "))

if stress > 7:
    print("⚠️ High stress! Reduce screen time.")
else:
    print("✅ Stress is under control.")

sns.barplot(x=['Screen Time','Stress'], y=[screen_time, stress])
plt.title("Your Mental Health Snapshot")
plt.show()